---

- name: MMMM TOTOT Display file contents      
  ansible.builtin.command: "cat {{ printfile_show_file }}"
  register: command_output
  changed_when: false

- name: Print file contents
  ansible.builtin.debug:
    msg: "{{ command_output.stdout }}"
